include colors.conf

font_family Hack
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12

window_padding_width 6
window_border_width 0
background_opacity 0.8

shell .
editor .

allow_remote_control yes
listen_on unix:/tmp/kitty

select_by_window_characters 1
url_style curly
open_url_with default

strip_trailing_spaces smart

mouse_hide_wait 2.0

# Fix: shortcuts work regardless of keyboard layout
clear_all_shortcuts yes

kitty_mod ctrl+shift
map kitty_mod+c copy_to_clipboard
map kitty_mod+с copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+м paste_from_clipboard
map kitty_mod+s paste_from_selection
map kitty_mod+ы paste_from_selection
map kitty_mod+a select_all
map kitty_mod+ф select_all
map kitty_mod+shift+left previous_tab
map kitty_mod+shift+right next_tab
map kitty_mod+t new_tab
map kitty_mod+е new_tab
map kitty_mod+w close_tab
map kitty_mod+ц close_tab
map kitty_mod+left move_tab_backward
map kitty_mod+right move_tab_forward
map kitty_mod+l next_layout
map kitty_mod+д next_layout
map kitty_mod+plus change_font_size all +1.0
map kitty_mod+minus change_font_size all -1.0
map kitty_mod+0 change_font_size all 0
map kitty_mod+f5 load_config_file
map kitty_mod+u input_unicode_character
map kitty_mod+г input_unicode_character
map kitty_mod+` move_window_to_top
map kitty_mod+enter new_window
map kitty_mod+n new_os_window
map kitty_mod+т new_os_window
