backend = "glx";
vsync = true;
use-damage = true;

opacity-rule = [
  "85:class_g = 'Thunar'",
  "85:class_g = 'thunar'",
  "85:class_g = 'blueman-manager'",
  "85:class_g = 'Pavucontrol'",
  "85:class_g = 'nm-connection-editor'",
  "85:class_g = 'qt5ct'",
  "85:class_g = 'qt6ct'",
  "85:class_g = 'arandr'",
  "90:class_g = 'opencode-desktop'",
  "85:!focused && class_g = 'zen'"
];

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.6;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'dunst'",
  "_GTK_FRAME_EXTENTS"
];

corner-radius = 14.0;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'dwm'",
  "class_g = 'Rofi'",
  "class_g = 'rofi'",
  "class_g = 'i3-frame'",
];

blur: {
  method = "dual_kawase";
  strength = 6;
  background = true;
  background-frame = false;
  background-fixed = false;
};

blur-background-exclude = [
  "class_g = 'slop'",
  "_GTK_FRAME_EXTENTS"
];

wintypes: {
  normal = { fade = false; shadow = true; }
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; }
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.9; }
  dropdown_menu = { opacity = 0.9; }
  notification = { opacity = 0.85; }
};
