[General]

Background="Backgrounds/login.png"
DimBackgroundImage="0.0"
ScaleImageCropped="true"
ScreenWidth="1920"
ScreenHeight="1080"

FullBlur="false"
PartialBlur="true"
BlurRadius="100"

HaveFormBackground="true"
FormPosition="center"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"

MainColor="#b0b3b8"
AccentColor="#979fa5"
BackgroundColor="#111a1e"
OverrideLoginButtonTextColor=""

InterfaceShadowSize="6"
InterfaceShadowOpacity="0.6"
RoundCorners="20"
ScreenPadding="0"
Font="Hack"
FontSize=""

ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="false"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d of MMMM"

HeaderText="Welcome!"
TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""
